//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_profile_Log
    {
        public int profid { get; set; }
        public Nullable<decimal> regid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string maidenname { get; set; }
        public string dob { get; set; }
        public string sex { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public Nullable<int> pin { get; set; }
        public string mobile { get; set; }
        public string eMail { get; set; }
        public string payeename { get; set; }
        public string panno { get; set; }
        public string bank { get; set; }
        public string branch { get; set; }
        public string accno { get; set; }
        public string ifscode { get; set; }
        public string nominee { get; set; }
        public string relation { get; set; }
        public string nomineedob { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string sessid { get; set; }
        public string ipaddress { get; set; }
        public string CorCity { get; set; }
        public string CorDistrict { get; set; }
        public string CorState { get; set; }
        public Nullable<int> CorPin { get; set; }
        public string GSTNO { get; set; }
    }
}
