//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConsultPayment
    {
        public decimal Slno { get; set; }
        public decimal Regid { get; set; }
        public string Mop { get; set; }
        public string MopNo { get; set; }
        public Nullable<System.DateTime> MopDate { get; set; }
        public string MopBank { get; set; }
        public string MopBranch { get; set; }
        public decimal Amount { get; set; }
        public string Sesid { get; set; }
        public string DDNo { get; set; }
        public string ChequeNo { get; set; }
        public string vouchercode { get; set; }
        public int Pstatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ordsts { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveSBODate { get; set; }
        public string appremarks { get; set; }
    }
}
