//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMemStsLog
    {
        public int CMSLId { get; set; }
        public decimal Regid { get; set; }
        public Nullable<int> Osts { get; set; }
        public Nullable<int> NSts { get; set; }
        public string Remarks { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Sesid { get; set; }
    }
}
