//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatement_Log
    {
        public int Bsid { get; set; }
        public string ReqCode { get; set; }
        public Nullable<decimal> CreditAmt { get; set; }
        public Nullable<System.DateTime> StmDate { get; set; }
        public string Bank { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Description { get; set; }
        public string ipaddress { get; set; }
        public string sessid { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string TranType { get; set; }
    }
}
