//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockSBOID
    {
        public int BSBOId { get; set; }
        public decimal Regid { get; set; }
        public Nullable<int> Osts { get; set; }
        public Nullable<int> NSts { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> StsDate { get; set; }
        public string Type { get; set; }
    }
}
