//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkMail
    {
        public int MAILID { get; set; }
        public string MAILFROM { get; set; }
        public string MAILTO { get; set; }
        public string SUBJECT { get; set; }
        public string MSG { get; set; }
        public Nullable<System.DateTime> SENTDATE { get; set; }
        public bool MREAD { get; set; }
        public string REPLY_ORGID { get; set; }
        public string FOR_ORGID { get; set; }
        public bool DELETED { get; set; }
        public bool SAVEnSEND { get; set; }
        public bool DELSENDER { get; set; }
        public bool DELREC { get; set; }
        public bool TRASH { get; set; }
        public bool NOTRASH { get; set; }
        public byte[] FILE1 { get; set; }
        public bool DRAFT { get; set; }
    }
}
