//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelDispOrder
    {
        public int SNo { get; set; }
        public Nullable<int> Regid { get; set; }
        public string InvoiceNo { get; set; }
        public string SessId { get; set; }
        public Nullable<int> Delby { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
