//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelOrders_Log
    {
        public int SlNo { get; set; }
        public Nullable<decimal> Regid { get; set; }
        public string Billno { get; set; }
        public string PlanType { get; set; }
        public string OrderType { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OldSts { get; set; }
        public Nullable<int> NewSts { get; set; }
        public string Remarks { get; set; }
    }
}
