//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChgAddress
    {
        public decimal Slno { get; set; }
        public decimal regid { get; set; }
        public System.DateTime reqdate { get; set; }
        public string MaidenName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Mobile { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string EMail { get; set; }
        public int changed { get; set; }
        public Nullable<System.DateTime> chgdate { get; set; }
        public Nullable<int> thru { get; set; }
        public string Remarks { get; set; }
        public string CorDistrict { get; set; }
        public string CorState { get; set; }
        public string CorCity { get; set; }
        public Nullable<int> CorPin { get; set; }
        public string GSTNO { get; set; }
    }
}
