//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class chgbank
    {
        public decimal Slno { get; set; }
        public decimal regid { get; set; }
        public System.DateTime reqdate { get; set; }
        public string PayeeName { get; set; }
        public string panno { get; set; }
        public string Bank { get; set; }
        public string Accno { get; set; }
        public string Branch { get; set; }
        public string Ifscode { get; set; }
        public int changed { get; set; }
        public Nullable<System.DateTime> chgdate { get; set; }
        public Nullable<int> thru { get; set; }
    }
}
