//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class chgdisc
    {
        public decimal Slno { get; set; }
        public string pcode { get; set; }
        public System.DateTime chgdate { get; set; }
        public decimal OldDisc { get; set; }
        public decimal NewDisc { get; set; }
        public string Sesid { get; set; }
        public string changedby { get; set; }
        public Nullable<decimal> oldpv { get; set; }
        public Nullable<decimal> newpv { get; set; }
    }
}
