//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CnF_StockOrder
    {
        public decimal slno { get; set; }
        public string RefNo { get; set; }
        public System.DateTime RefDate { get; set; }
        public string Fcode { get; set; }
        public string Packcode { get; set; }
        public int qty { get; set; }
        public decimal NetAmt { get; set; }
        public string Remarks { get; set; }
        public string status { get; set; }
        public string sesid { get; set; }
        public string UQID { get; set; }
        public string AppRejBy { get; set; }
        public Nullable<System.DateTime> AppRejDate { get; set; }
        public string Mode { get; set; }
        public string MODName { get; set; }
        public string MODNo { get; set; }
        public Nullable<System.DateTime> MODDate { get; set; }
        public string MODRemarks { get; set; }
        public string DisType { get; set; }
        public string levelstatus { get; set; }
        public string InvNo { get; set; }
        public string CFAName_From { get; set; }
        public string CFAName_To { get; set; }
        public decimal TotalTransferPrice { get; set; }
        public decimal TotalBP { get; set; }
        public decimal TaxAmt_IGST { get; set; }
        public decimal TaxAmt_CGST { get; set; }
        public decimal TaxAmt_SGST { get; set; }
        public int TaxType { get; set; }
        public string VehicleNo { get; set; }
        public int StateType { get; set; }
    }
}
