//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CnF_Outward
    {
        public decimal slno { get; set; }
        public string Fcode { get; set; }
        public string RefNo { get; set; }
        public string Itemcode { get; set; }
        public string Packcode { get; set; }
        public int qty { get; set; }
        public System.DateTime RefDate { get; set; }
        public string sesid { get; set; }
        public string TransferType { get; set; }
        public string Remarks { get; set; }
        public string status { get; set; }
        public string OrdRefNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string SesUser { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> MgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public decimal DRegid { get; set; }
        public System.DateTime RecDate { get; set; }
        public decimal MRP { get; set; }
        public string PType { get; set; }
        public int RefNoGenKey { get; set; }
        public int PackageId { get; set; }
    }
}
