//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeError
    {
        public int Sno { get; set; }
        public string userid { get; set; }
        public string Pageurl { get; set; }
        public string ErrorMsg { get; set; }
        public string sesid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
