//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMeeting
    {
        public int CMId { get; set; }
        public string Name { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> Mdate { get; set; }
        public string MTime { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
