//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode
    {
        public int Sno { get; set; }
        public string CouponCode1 { get; set; }
        public Nullable<int> Assigned { get; set; }
        public Nullable<decimal> Regid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Pcode { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<decimal> OrginalPrice { get; set; }
        public Nullable<decimal> CouponPrice { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
    }
}
