//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierNo
    {
        public decimal Sno { get; set; }
        public string Courier { get; set; }
        public string DocNo { get; set; }
        public byte Status { get; set; }
        public System.DateTime Dated { get; set; }
        public string SesUser { get; set; }
        public string SesID { get; set; }
        public string Billno { get; set; }
        public Nullable<decimal> BillRegid { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    }
}
