//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRequestOnline
    {
        public decimal Sno { get; set; }
        public Nullable<decimal> regid { get; set; }
        public Nullable<decimal> reqAmt { get; set; }
        public string mop { get; set; }
        public string Refno { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public string invbank { get; set; }
        public string invbranch { get; set; }
        public string depbank { get; set; }
        public string depbranch { get; set; }
        public string depcity { get; set; }
        public Nullable<System.DateTime> depdate { get; set; }
        public string depslip { get; set; }
        public string remarks { get; set; }
        public string ORDER_ID { get; set; }
        public string PaymentStatus { get; set; }
        public string BillStatus { get; set; }
        public string TXNID { get; set; }
        public string Recode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string pgtype { get; set; }
        public string PGTranStatus { get; set; }
    }
}
