//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRequest_CnF
    {
        public int CRid { get; set; }
        public string ReqCode { get; set; }
        public string Fcode { get; set; }
        public Nullable<decimal> RequestAmt { get; set; }
        public string MOP { get; set; }
        public string InsNo { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string InsBank { get; set; }
        public string InsBranch { get; set; }
        public int ReqStatus { get; set; }
        public System.DateTime Reqdate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string DepBank { get; set; }
        public string DepBranch { get; set; }
        public string DepCity { get; set; }
        public Nullable<System.DateTime> DepDate { get; set; }
        public string DepSlip { get; set; }
        public string UserType { get; set; }
        public string AdminRemarks { get; set; }
        public int PayType { get; set; }
        public string Packcode { get; set; }
    }
}
