//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class deleteTempCart_log
    {
        public int Sno { get; set; }
        public Nullable<int> Pcode { get; set; }
        public string Itemcode { get; set; }
        public string attribute { get; set; }
        public Nullable<int> qty { get; set; }
        public string unqid { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<System.DateTime> Deldate { get; set; }
        public string tablename { get; set; }
        public Nullable<System.DateTime> prodorddate { get; set; }
    }
}
