//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPBatchMaster
    {
        public decimal slno { get; set; }
        public string DESPBNo { get; set; }
        public Nullable<decimal> NoInv { get; set; }
        public string Courier { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Remarks { get; set; }
        public string sessid { get; set; }
    }
}
