//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPBatchItem
    {
        public decimal slno { get; set; }
        public string DESPBNo { get; set; }
        public string Invno { get; set; }
        public string DockNo { get; set; }
        public Nullable<System.DateTime> DockDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string DelStatus { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string RecStatus { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string RecBy { get; set; }
        public Nullable<decimal> Regid { get; set; }
    }
}
