//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPBatchExcel
    {
        public decimal slno { get; set; }
        public string Invno { get; set; }
        public string DockNo { get; set; }
        public Nullable<System.DateTime> DockDate { get; set; }
        public string Status { get; set; }
    }
}
