//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistshipCancellationRpt
    {
        public int Sno { get; set; }
        public Nullable<int> Regid { get; set; }
        public string Idno { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public Nullable<int> Mstatus { get; set; }
        public Nullable<System.DateTime> creteddate { get; set; }
    }
}
