//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downloadfile
    {
        public int Sno { get; set; }
        public string Title { get; set; }
        public string Downloadfile1 { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Uploadby { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string sesid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
