//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarlRankTree
    {
        public decimal Aid { get; set; }
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal RefFormNo { get; set; }
        public decimal RefLegNo { get; set; }
        public decimal SelfIncentive { get; set; }
        public decimal DwnIncentive { get; set; }
        public decimal Incentive { get; set; }
        public decimal Slab { get; set; }
        public decimal Comm { get; set; }
    }
}
