//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarlRankTreeRelation
    {
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal LegNo { get; set; }
        public decimal MLevel { get; set; }
        public decimal Comm { get; set; }
        public decimal SessID { get; set; }
        public decimal SelfSlab { get; set; }
        public decimal DownSlab { get; set; }
    }
}
