//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarlTreasureAch
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal LegNo { get; set; }
        public decimal IsPower { get; set; }
        public decimal Viscount { get; set; }
        public decimal Earl { get; set; }
        public decimal Bv { get; set; }
    }
}
