//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDSAbulkmailLog
    {
        public decimal SNo { get; set; }
        public string Email { get; set; }
        public string Subj { get; set; }
        public string Msg { get; set; }
        public string Thru { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Name { get; set; }
    }
}
