//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FBid { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Enquiry { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<bool> FStatus { get; set; }
        public string sessid { get; set; }
        public string address { get; set; }
        public string QType { get; set; }
        public string pincode { get; set; }
        public string Idno { get; set; }
    }
}
