//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchisee
    {
        public decimal FID { get; set; }
        public string Fcode { get; set; }
        public string fname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Email { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string DeletedBY { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> StkLimit { get; set; }
        public Nullable<decimal> JoinAmt { get; set; }
        public string CPName { get; set; }
        public string regid { get; set; }
        public string Bank { get; set; }
        public string AccountNo { get; set; }
        public string IFCS { get; set; }
        public string BankAddress { get; set; }
        public string TinNo { get; set; }
        public string GST { get; set; }
    }
}
