//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fundwithdrawl
    {
        public decimal SNo { get; set; }
        public decimal ReqID { get; set; }
        public decimal FormNo { get; set; }
        public decimal ReqAmount { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Status { get; set; }
        public string PanNo { get; set; }
        public Nullable<decimal> RndOff { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string PayeeName { get; set; }
        public string AcNo { get; set; }
        public Nullable<decimal> BankID { get; set; }
        public string BranchName { get; set; }
        public string IFSCode { get; set; }
        public decimal wSessID { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public string PaymentMode { get; set; }
    }
}
