//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftChallan
    {
        public int SNo { get; set; }
        public string ReqNo { get; set; }
        public int Regid { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> Pcode { get; set; }
        public string Pname { get; set; }
        public string Attrib { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Sts { get; set; }
        public Nullable<int> Dispsts { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> AppRejDate { get; set; }
        public string IPAddress { get; set; }
        public string SessID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string StoreSessID { get; set; }
        public Nullable<int> Appby { get; set; }
        public string SRemarks { get; set; }
        public string CourName { get; set; }
        public string DocNo { get; set; }
        public string ChallanNo { get; set; }
        public string Invno { get; set; }
    }
}
