//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GVDInstalment
    {
        public int SNo { get; set; }
        public int Regid { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<decimal> PackAmt { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Mop { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Sessid { get; set; }
        public string IPAdd { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string billno { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Appby { get; set; }
        public Nullable<System.DateTime> ExtendDate { get; set; }
        public string DDno { get; set; }
        public Nullable<System.DateTime> dddate { get; set; }
        public string bank { get; set; }
        public string branch { get; set; }
        public string Unqid { get; set; }
    }
}
