//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public int MAILID { get; set; }
        public string MAILFROM { get; set; }
        public string MAILTO { get; set; }
        public string MSUB { get; set; }
        public string MSG { get; set; }
        public System.DateTime SENTDATE { get; set; }
        public Nullable<bool> MREAD { get; set; }
        public string REPLY_ORGID { get; set; }
        public string FOR_ORGID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<bool> SAVEnSEND { get; set; }
        public Nullable<bool> DELSENDER { get; set; }
        public bool DELREC { get; set; }
        public Nullable<bool> TRASH { get; set; }
        public Nullable<bool> NOTRASH { get; set; }
        public string FILE1 { get; set; }
        public Nullable<bool> DRAFT { get; set; }
        public bool FSTATUS { get; set; }
        public Nullable<int> FOLDERID { get; set; }
        public string ToType { get; set; }
        public string ReqNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
    }
}
