//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalPaymentOnline
    {
        public int SNo { get; set; }
        public string Uniqid { get; set; }
        public string billno { get; set; }
        public Nullable<int> Regid { get; set; }
        public Nullable<int> Pid { get; set; }
        public string Mop { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string SessId { get; set; }
        public string PaymetSts { get; set; }
        public string BillSts { get; set; }
        public string TransID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> RespDate { get; set; }
    }
}
