//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceOffer
    {
        public int Sno { get; set; }
        public string InvCode { get; set; }
        public string OffName { get; set; }
        public Nullable<decimal> InvValue { get; set; }
        public Nullable<System.DateTime> validFromdate { get; set; }
        public Nullable<System.DateTime> validTodate { get; set; }
        public Nullable<int> Sts { get; set; }
        public string IPAddress { get; set; }
        public string SessID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Maxval { get; set; }
    }
}
