//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMaster_CnF
    {
        public int SNo { get; set; }
        public string InvoiceNo { get; set; }
        public string Fcode { get; set; }
        public string State { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> status { get; set; }
        public string Fcode_From { get; set; }
        public int SuqNo { get; set; }
    }
}
