//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPrddetail
    {
        public int Sno { get; set; }
        public string Uniqid { get; set; }
        public Nullable<int> Regid { get; set; }
        public Nullable<int> Pcode { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string itemcode { get; set; }
        public string Attrname { get; set; }
    }
}
