//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        public decimal ItemId { get; set; }
        public string ItemCode1 { get; set; }
        public string PCode { get; set; }
        public Nullable<int> RPCId { get; set; }
        public string Attrib1 { get; set; }
        public string Attrib2 { get; set; }
        public string Attrib3 { get; set; }
        public string Attrib4 { get; set; }
        public string Attrib5 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> myChoice { get; set; }
        public string descr { get; set; }
        public string Attrib6 { get; set; }
        public string Attrib7 { get; set; }
        public string Attrib8 { get; set; }
        public string Attrib9 { get; set; }
        public string Attrib10 { get; set; }
    }
}
