//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public decimal SessId { get; set; }
        public decimal FormNo { get; set; }
        public decimal Amount { get; set; }
        public string CrDr { get; set; }
        public string VType { get; set; }
        public Nullable<System.DateTime> VDate { get; set; }
        public string PayMode { get; set; }
        public decimal BankId { get; set; }
        public string ChNo { get; set; }
        public decimal RefNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public string ClearStatus { get; set; }
        public string Remark { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public string PanNo { get; set; }
        public string TRANSFERBY { get; set; }
        public string Status { get; set; }
        public decimal TNo { get; set; }
        public decimal PNo { get; set; }
        public string ChqStatus { get; set; }
        public string IsShow { get; set; }
        public string PurchaseStatus { get; set; }
        public string AppType { get; set; }
    }
}
