//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelidsSPR
    {
        public decimal lvlid { get; set; }
        public decimal Regid { get; set; }
        public string Spseries { get; set; }
        public decimal Thru { get; set; }
        public decimal Lvl { get; set; }
        public int leg { get; set; }
    }
}
