//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int Lid { get; set; }
        public string LinkName { get; set; }
        public string Pagename { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Nav { get; set; }
        public Nullable<int> sorting { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string sesid { get; set; }
        public string usertype { get; set; }
        public string Icon { get; set; }
        public string Memtype { get; set; }
    }
}
