//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOnlineDataEBSNew
    {
        public int Lid { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public string DateCreated { get; set; }
        public string PaymentID { get; set; }
        public string MerchantRefNo { get; set; }
        public string Amount { get; set; }
        public string Mode { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPhone { get; set; }
        public string BillingEmail { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryPostalCode { get; set; }
        public string DeliveryCountry { get; set; }
        public string DeliveryPhone { get; set; }
        public string Description { get; set; }
        public string IsFlagged { get; set; }
        public string TransactionID { get; set; }
        public string PaymentMethod { get; set; }
        public string RequestID { get; set; }
        public string SecureHash { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
