//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOnlineDataNew
    {
        public int Lid { get; set; }
        public string SUBS_ID { get; set; }
        public string MID { get; set; }
        public string TXNID { get; set; }
        public string ORDERID { get; set; }
        public string BANKTXNID { get; set; }
        public string TXNAMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string STATUS { get; set; }
        public string RESPCODE { get; set; }
        public string RESPMSG { get; set; }
        public Nullable<System.DateTime> TXNDATE { get; set; }
        public string GATEWAYNAME { get; set; }
        public string BANKNAME { get; set; }
        public string PAYMENTMODE { get; set; }
        public string PROMO_CAMP_ID { get; set; }
        public string PROMO_STATUS { get; set; }
        public string PROMO_RESPCODE { get; set; }
        public string CHECKSUMHASH { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
