//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MemTreeRelation
    {
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal LegNo { get; set; }
        public Nullable<decimal> MLevel { get; set; }
    }
}
