//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MonthWiseIncome
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal Slab { get; set; }
        public decimal RetailProfit { get; set; }
        public decimal LeverageBonus { get; set; }
        public decimal PPBonus { get; set; }
        public decimal MRSB { get; set; }
        public decimal LPB { get; set; }
        public decimal EarlTreasure { get; set; }
        public decimal DiamondTreasure { get; set; }
        public decimal PPTreasure { get; set; }
        public decimal ConsistencyTreasure { get; set; }
        public decimal C25KTreasure { get; set; }
        public decimal RoyaltyIncome { get; set; }
        public decimal NetIncome { get; set; }
        public decimal TdsOnAmount { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal CouponsAmt { get; set; }
        public decimal PrevBal { get; set; }
        public decimal ChqAmt { get; set; }
        public decimal ClsBal { get; set; }
        public string Remarks { get; set; }
        public decimal AdjAmt { get; set; }
        public decimal RndOff { get; set; }
        public string PanNo { get; set; }
        public decimal MatchIncome { get; set; }
    }
}
