//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MonthWiseBv
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal SelfBv { get; set; }
        public decimal DownBv { get; set; }
        public decimal TotalBv { get; set; }
        public decimal SelfBvCum { get; set; }
        public decimal DownBvCum { get; set; }
        public decimal TotalBvCum { get; set; }
        public decimal Slab { get; set; }
        public Nullable<decimal> Remark { get; set; }
        public decimal RankID { get; set; }
        public decimal ReqBv { get; set; }
        public decimal NonVCBv { get; set; }
        public decimal ProgInc { get; set; }
        public decimal SelfInc { get; set; }
        public decimal MRSBCnt { get; set; }
        public decimal MRSB { get; set; }
        public decimal MRSBType { get; set; }
        public decimal SessSlab { get; set; }
        public string IsElig { get; set; }
        public decimal PowerBv { get; set; }
        public decimal OtherBv { get; set; }
        public string IsKYC { get; set; }
        public decimal C25KCnt { get; set; }
        public decimal MatchBv { get; set; }
        public decimal MatchCnt { get; set; }
        public decimal PwrCF { get; set; }
        public decimal WkrCF { get; set; }
        public string IsLoyal { get; set; }
        public decimal ExtraBv { get; set; }
        public decimal ETSlab { get; set; }
        public decimal DTSlab { get; set; }
        public decimal PPTSlab { get; set; }
        public decimal CT { get; set; }
        public decimal PowerBvCur { get; set; }
        public decimal OtherBvCur { get; set; }
        public decimal PowerEarl { get; set; }
        public decimal OtherEarl { get; set; }
        public decimal SelfBvExt { get; set; }
        public decimal DownBvExt { get; set; }
        public decimal SelfBvCumExt { get; set; }
        public decimal DownBvCumExt { get; set; }
        public decimal NonVCExtBv { get; set; }
        public decimal NonVCSessBv { get; set; }
        public decimal NonVCSessExtBv { get; set; }
    }
}
