//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MonthlyPayDetail
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal PairIncome { get; set; }
        public decimal PairIncomeAct { get; set; }
        public decimal MagicIncome { get; set; }
        public decimal RoyaltyIncome { get; set; }
        public decimal PairIncentive { get; set; }
        public decimal BonusIncome { get; set; }
        public decimal ExtraBonus { get; set; }
        public decimal NetIncome { get; set; }
        public decimal TdsOnAmount { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal CouponsAmt { get; set; }
        public decimal PrevBal { get; set; }
        public decimal ChqAmt { get; set; }
        public decimal ClsBal { get; set; }
        public string Remarks { get; set; }
        public decimal AdjAmt { get; set; }
        public decimal RoundOff { get; set; }
        public decimal ServiceTax { get; set; }
        public string IsShow { get; set; }
        public decimal RefId { get; set; }
        public decimal RewardIncome { get; set; }
        public decimal BoosterIncome { get; set; }
        public decimal BoosterIncomeAct { get; set; }
        public decimal BoosterBonus { get; set; }
    }
}
