//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NONVCSESSNPV
    {
        public decimal ID { get; set; }
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal MLevel { get; set; }
        public decimal SelfRank { get; set; }
        public decimal DownRank { get; set; }
        public decimal PV { get; set; }
        public decimal GPV { get; set; }
        public decimal ExtPv { get; set; }
    }
}
