//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_RetailProfit
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal BillAmt { get; set; }
        public decimal Slab { get; set; }
        public decimal Comm { get; set; }
    }
}
