//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SessWiseBv
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal PwrLeg { get; set; }
        public decimal WkrLeg { get; set; }
        public decimal Total { get; set; }
        public decimal PwrLegCum { get; set; }
        public decimal WkrLegCum { get; set; }
        public decimal TotalCum { get; set; }
        public decimal PwrLegBv { get; set; }
        public decimal WkrLegBv { get; set; }
        public decimal SelfBv { get; set; }
        public decimal SelfBvRe { get; set; }
        public decimal TotalBv { get; set; }
        public decimal PwrLegBvCum { get; set; }
        public decimal WkrLegBvCum { get; set; }
        public decimal SelfBvCum { get; set; }
        public decimal SelfBvReCum { get; set; }
        public decimal TotalBvCum { get; set; }
        public decimal Slab { get; set; }
        public decimal RoyaltySlab { get; set; }
        public decimal Remark { get; set; }
        public decimal LegXBv { get; set; }
        public decimal LegYBv { get; set; }
        public decimal LegXBvCum { get; set; }
        public decimal LegYBvCum { get; set; }
        public decimal LegXBvCF { get; set; }
        public decimal LegYBvCF { get; set; }
        public Nullable<decimal> FirstPairIncome { get; set; }
        public decimal TriIncome { get; set; }
        public decimal NonetIncome1 { get; set; }
        public decimal RP { get; set; }
        public decimal Quint1 { get; set; }
        public decimal NonetIncome2 { get; set; }
        public decimal Quint2 { get; set; }
        public string Calc { get; set; }
        public decimal LegXBvRe { get; set; }
        public decimal LegYBvRe { get; set; }
        public decimal LegXBvSelf { get; set; }
        public decimal LegYBvSelf { get; set; }
    }
}
