//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UserMaster
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Passw { get; set; }
        public string AStatus { get; set; }
        public System.DateTime RTS { get; set; }
    }
}
