//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_AndroidAccess
    {
        public decimal Sno { get; set; }
        public string Userid { get; set; }
        public byte[] Pwd { get; set; }
        public string MobInfo { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Msg { get; set; }
        public string Gcmid { get; set; }
    }
}
