//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public int MId { get; set; }
        public Nullable<int> Regid { get; set; }
        public Nullable<System.DateTime> Senddate { get; set; }
        public string MailType { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public string Sesid { get; set; }
        public string SendTo { get; set; }
    }
}
