//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mastermop_PKGInvChg_150717
    {
        public decimal regid { get; set; }
        public string idno { get; set; }
        public string Name { get; set; }
        public string billno { get; set; }
        public System.DateTime challandt { get; set; }
        public Nullable<System.DateTime> commdate { get; set; }
        public Nullable<decimal> totalamt { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public string invoiceno { get; set; }
    }
}
