//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterMOP_ManualOrders_Ins
    {
        public int Sno { get; set; }
        public string BillNo { get; set; }
        public string ReqNo { get; set; }
        public string ORDER_ID { get; set; }
        public string TrasactionID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
