//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_photos
    {
        public decimal Slno { get; set; }
        public decimal regid { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string ipadd { get; set; }
        public string sesid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> adated { get; set; }
        public string asesid { get; set; }
        public string aipadd { get; set; }
        public string path { get; set; }
        public string ByUser { get; set; }
    }
}
