//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddress
    {
        public decimal MAid { get; set; }
        public decimal Regid { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public Nullable<long> Pin { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string CorCity { get; set; }
        public string CorDistrict { get; set; }
        public string CorState { get; set; }
        public Nullable<long> CorPin { get; set; }
        public string Landline { get; set; }
        public string AltMobile { get; set; }
        public string CorAdd1 { get; set; }
        public string CorAdd2 { get; set; }
    }
}
