//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPayment
    {
        public decimal MPid { get; set; }
        public decimal regid { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Ifscode { get; set; }
        public string ReferenceType { get; set; }
    }
}
