//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberUpgrade_log
    {
        public decimal slno { get; set; }
        public decimal regid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string OldMgroup { get; set; }
        public string NewMgroup { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UID { get; set; }
        public string Sesid { get; set; }
        public Nullable<decimal> bv { get; set; }
        public Nullable<int> Mstatus { get; set; }
        public Nullable<System.DateTime> Logdate { get; set; }
    }
}
