//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberIHO
    {
        public int SNo { get; set; }
        public Nullable<decimal> regid { get; set; }
        public string ProofType { get; set; }
        public string IHOPhoto { get; set; }
        public string ChqLeaf { get; set; }
        public Nullable<int> IHOStatus { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public string Sesid { get; set; }
        public Nullable<int> AppRejBy { get; set; }
        public Nullable<System.DateTime> AppRejDate { get; set; }
        public string AppRejSesid { get; set; }
        public string AppRejRemarks { get; set; }
        public Nullable<int> Dispstatus { get; set; }
        public Nullable<int> Dockstatus { get; set; }
        public string CourierDetails { get; set; }
        public string IHONO { get; set; }
        public string DockNo { get; set; }
        public Nullable<System.DateTime> DockDate { get; set; }
        public string DockUpdatedby { get; set; }
    }
}
