//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPhoto
    {
        public int MPID { get; set; }
        public decimal regid { get; set; }
        public string MPhoto { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Reqsts { get; set; }
        public string Remarks { get; set; }
    }
}
