//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfile
    {
        public decimal PrId { get; set; }
        public decimal Regid { get; set; }
        public string Idno { get; set; }
        public string Title { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MaidenName { get; set; }
        public string Maiden { get; set; }
        public string LPassword { get; set; }
        public string TPassword { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public int Sex { get; set; }
        public string Panno { get; set; }
        public string SesID { get; set; }
        public string GuardianName { get; set; }
        public string qualification { get; set; }
        public string subject { get; set; }
        public string GcmID { get; set; }
        public string username { get; set; }
        public string careof { get; set; }
        public string fullitemcode { get; set; }
        public string OldLpwd { get; set; }
        public string OldTpwd { get; set; }
        public string UniqUserName { get; set; }
        public string Imei { get; set; }
        public string Androidid { get; set; }
        public string Wlanmac { get; set; }
        public string GSTNO { get; set; }
    }
}
