//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberVoucher
    {
        public int VNo { get; set; }
        public decimal Regid { get; set; }
        public string VoucherID { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public int Uid { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
    }
}
