//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileSlide
    {
        public long Sno { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Sessid { get; set; }
        public string IpAdress { get; set; }
        public string MBImage { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string Updatedby { get; set; }
    }
}
