//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mopsale
    {
        public decimal slno { get; set; }
        public string mop { get; set; }
        public decimal regid { get; set; }
        public string billno { get; set; }
        public System.DateTime challandt { get; set; }
        public string ddno { get; set; }
        public Nullable<System.DateTime> dddate { get; set; }
        public string bank { get; set; }
        public string branch { get; set; }
        public decimal amount { get; set; }
        public string code { get; set; }
        public string repurno { get; set; }
        public string sesid { get; set; }
        public string oldbillno { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Rflag { get; set; }
        public Nullable<decimal> RAmt { get; set; }
        public string RMop { get; set; }
        public string RRemarks { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
    }
}
