//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstDiscountCoupon
    {
        public decimal Dcid { get; set; }
        public string CouponName { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Rectimestamp { get; set; }
        public string IsUSed { get; set; }
        public string Activestatus { get; set; }
        public decimal CouponID { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string TypeOfCoupons { get; set; }
        public string IsAssign { get; set; }
        public decimal Formno { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public decimal MinimumPurchase { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public decimal PNo { get; set; }
        public string DiscountOffer { get; set; }
        public string TimeBasedCoupon { get; set; }
        public string Category { get; set; }
        public string SizeKitid { get; set; }
        public decimal TestimonialId { get; set; }
        public decimal kitid { get; set; }
        public decimal SoldTo { get; set; }
        public string isCategory { get; set; }
        public Nullable<decimal> Catid { get; set; }
    }
}
