//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstKitMaster
    {
        public int KitID { get; set; }
        public string KitName { get; set; }
        public decimal KitAmount { get; set; }
        public decimal FullAmount { get; set; }
        public decimal AnnualMaintenance { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Educess { get; set; }
        public decimal PoolIncome { get; set; }
        public decimal KitUnit { get; set; }
        public decimal RefIncome { get; set; }
        public decimal SerialStart { get; set; }
        public string activestatus { get; set; }
        public decimal RewardPoint { get; set; }
        public decimal Capping { get; set; }
        public decimal LSUnit { get; set; }
        public decimal Period { get; set; }
        public decimal Maturity { get; set; }
        public decimal STaxAmount { get; set; }
        public decimal ECessAmount { get; set; }
        public decimal SCessAmount { get; set; }
        public decimal ROUNDOFF { get; set; }
        public decimal SpillIncome { get; set; }
        public decimal TOTALKITAMOUNT { get; set; }
        public decimal NETAMOUNT { get; set; }
        public string KITNAMEADMIN { get; set; }
        public string IsDisplay { get; set; }
        public string Remark { get; set; }
        public decimal AbatementSTaxAmount { get; set; }
        public string PStatus { get; set; }
        public string SPack { get; set; }
        public decimal BasicCost { get; set; }
        public decimal EduSTaxAmount { get; set; }
        public decimal EduECessAmount { get; set; }
        public decimal EduCCessAmount { get; set; }
        public decimal EduKitAmount { get; set; }
        public decimal BasicSTaxAmount { get; set; }
        public decimal BasicECessAmount { get; set; }
        public decimal BasicCCessAmount { get; set; }
        public string IsBonus { get; set; }
        public string IsEducation { get; set; }
        public string IsThialand { get; set; }
        public string IsSize { get; set; }
        public decimal CatID { get; set; }
        public string IsDesign { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public string IsDDStatus { get; set; }
        public decimal OldUnit { get; set; }
        public string IsShip { get; set; }
        public decimal SNo { get; set; }
        public string IsColor { get; set; }
        public string IStatus { get; set; }
        public string CStatus { get; set; }
        public string ImagePath { get; set; }
        public decimal MRP { get; set; }
        public decimal SubCatID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public string Features { get; set; }
        public string IsWeb { get; set; }
        public string StockStatus { get; set; }
        public string imagepath1 { get; set; }
        public string imagepath2 { get; set; }
        public string imagepath3 { get; set; }
        public string imagepath4 { get; set; }
        public string imagepath5 { get; set; }
        public string AddRs1 { get; set; }
        public string KitNameInvoice { get; set; }
        public string KitType { get; set; }
        public string ComboStatus { get; set; }
        public string Declaration { get; set; }
        public string KitnameDisplay { get; set; }
        public string NewArrival { get; set; }
        public decimal SBOPrice { get; set; }
        public decimal InvProductCode { get; set; }
        public string isLuckySize { get; set; }
        public decimal TotalStockInput { get; set; }
        public decimal TotalStockAvailable { get; set; }
        public decimal TotalStockUsed { get; set; }
        public decimal rownum { get; set; }
        public string VoucherType { get; set; }
        public Nullable<decimal> CvUnit { get; set; }
        public Nullable<decimal> DPPrice { get; set; }
    }
}
