//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRoyaltyGeneration
    {
        public decimal Aid { get; set; }
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal MLevel { get; set; }
        public string Generation { get; set; }
        public decimal Rn { get; set; }
        public decimal SelfRank { get; set; }
        public decimal DownSelfBv { get; set; }
        public decimal DownGroupBv { get; set; }
        public decimal DownTotalBv { get; set; }
        public decimal Slab { get; set; }
        public decimal BonusBv { get; set; }
        public decimal DwnRank { get; set; }
        public string IsQualify { get; set; }
    }
}
