//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRoyaltyBonu
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal SelfBv { get; set; }
        public decimal GroupBv { get; set; }
        public decimal TotalBv { get; set; }
        public decimal SelfSlab { get; set; }
        public decimal BonusBv { get; set; }
        public decimal DownBonusBv { get; set; }
        public decimal TotalBonusBv { get; set; }
        public decimal Rate { get; set; }
        public decimal Comm { get; set; }
        public decimal SelfRank { get; set; }
        public decimal TransferBv { get; set; }
    }
}
