//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRankUpdateUp
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal FormNodwn { get; set; }
        public decimal Hand { get; set; }
        public decimal Cnt { get; set; }
        public decimal RankID { get; set; }
        public string RankType { get; set; }
    }
}
