//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRoyaltySlab
    {
        public decimal MLevel { get; set; }
        public decimal Comm { get; set; }
        public string ActiveStatus { get; set; }
        public decimal RankID { get; set; }
    }
}
