//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstSessWiseBv
    {
        public decimal Aid { get; set; }
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal LegNo { get; set; }
        public decimal LegXBvSelf { get; set; }
        public decimal LegYBvSelf { get; set; }
        public decimal LegXBvRe { get; set; }
        public decimal LegYBvRe { get; set; }
        public decimal LegXBv { get; set; }
        public decimal LegYBv { get; set; }
        public decimal TriIncome { get; set; }
        public decimal NonetIncome1 { get; set; }
        public decimal RP { get; set; }
        public decimal Quint1 { get; set; }
        public decimal NonetIncome2 { get; set; }
        public decimal Quint2 { get; set; }
        public decimal TotalAmt { get; set; }
        public string Calc { get; set; }
        public decimal PayAmt { get; set; }
        public decimal Sales { get; set; }
        public decimal UptoSales { get; set; }
        public decimal LegXBvCum { get; set; }
        public decimal LegYBvCum { get; set; }
        public decimal LegXBvBF { get; set; }
        public decimal LegYBvBF { get; set; }
        public decimal LegXBvNew { get; set; }
        public decimal LegYBvNew { get; set; }
        public decimal LegXBvTotal { get; set; }
        public decimal LegYBvTotal { get; set; }
        public decimal LegXBvPaid { get; set; }
        public decimal LegYBvPaid { get; set; }
        public decimal LegXBvCF { get; set; }
        public decimal LegYBvCF { get; set; }
        public decimal AddOn { get; set; }
    }
}
