//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstStoreProductId
    {
        public decimal Sid { get; set; }
        public decimal Formno { get; set; }
        public decimal ProductId { get; set; }
        public System.DateTime Doj { get; set; }
        public decimal MPId { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public string Pstatus { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public decimal Bv { get; set; }
        public string AppType { get; set; }
        public decimal SysOrderNo { get; set; }
    }
}
