//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public decimal NoteID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public decimal regid { get; set; }
        public Nullable<int> Registration { get; set; }
        public Nullable<int> EwalletReq { get; set; }
        public Nullable<int> ForgotPwd { get; set; }
        public Nullable<int> CompnyNotify { get; set; }
        public Nullable<int> EwalltTranstion { get; set; }
    }
}
