//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMaster
    {
        public int NMID { get; set; }
        public string Category { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
