//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferInfoPosting
    {
        public int Sno { get; set; }
        public Nullable<int> Regid { get; set; }
        public string OfferCode { get; set; }
        public Nullable<decimal> WalletValue { get; set; }
        public Nullable<int> PackCode { get; set; }
        public Nullable<int> pid { get; set; }
        public string billno { get; set; }
        public string Offtype { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
