//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferProduct
    {
        public int Sno { get; set; }
        public string InvCode { get; set; }
        public Nullable<int> Pcode { get; set; }
        public Nullable<decimal> InvValue { get; set; }
        public Nullable<int> PrdSts { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> Maxval { get; set; }
    }
}
