//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffPrductsList
    {
        public int Sno { get; set; }
        public string ReqCode { get; set; }
        public Nullable<int> Pcode { get; set; }
        public Nullable<int> OffPcode { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> PrdSts { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
