//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageMaster
    {
        public int PID { get; set; }
        public string PackCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> BV { get; set; }
        public Nullable<bool> PStatus { get; set; }
        public string Remarks { get; set; }
        public string plantype { get; set; }
        public Nullable<decimal> Discamt { get; set; }
        public Nullable<decimal> unitcomm { get; set; }
        public Nullable<int> RegType { get; set; }
        public string PostEwallet { get; set; }
        public Nullable<decimal> DRCAmt { get; set; }
        public Nullable<bool> PkgType { get; set; }
        public Nullable<System.DateTime> CreatdOn { get; set; }
        public decimal taxamt { get; set; }
        public string fullitemcode { get; set; }
        public string offer { get; set; }
        public Nullable<int> Combosts { get; set; }
        public int OffSts { get; set; }
    }
}
