//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItem
    {
        public decimal slno { get; set; }
        public string PackCode { get; set; }
        public string pcode { get; set; }
        public Nullable<int> qty { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool status { get; set; }
        public string sesid { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> taxper { get; set; }
        public Nullable<decimal> iprice { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> RPCId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string SubCategoryone { get; set; }
        public string OffType { get; set; }
        public Nullable<decimal> CV { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
    }
}
