//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SICP_ErrorDetails
    {
        public int Sno { get; set; }
        public int Payno { get; set; }
        public string ErrorMsg { get; set; }
        public string ErrorLine { get; set; }
    }
}
