//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMP_AccInfo_RP
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public Nullable<System.DateTime> SchFrom { get; set; }
        public Nullable<System.DateTime> SchTo { get; set; }
        public Nullable<decimal> SchInc { get; set; }
        public Nullable<decimal> BFAmt { get; set; }
        public Nullable<decimal> GrAmt { get; set; }
        public Nullable<decimal> SC { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<decimal> AdvDed { get; set; }
        public Nullable<decimal> NetElgAmt { get; set; }
        public string AdvDedRem { get; set; }
        public string Remarks { get; set; }
        public string TypeOfInc { get; set; }
        public Nullable<int> PayNo { get; set; }
        public string PanNo { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
