//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_DesgMaster
    {
        public int SNo { get; set; }
        public int DesgNo { get; set; }
        public string DesgName { get; set; }
        public Nullable<decimal> GCV { get; set; }
        public Nullable<int> QlfCnt { get; set; }
        public Nullable<decimal> QlfyBV { get; set; }
        public Nullable<int> QlfyPer { get; set; }
        public Nullable<decimal> AstFund { get; set; }
        public Nullable<decimal> AstCeiling { get; set; }
        public string AstType { get; set; }
    }
}
