//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_orbit_Booster
    {
        public int sno { get; set; }
        public Nullable<decimal> Uplnformno { get; set; }
        public Nullable<decimal> FormNo { get; set; }
        public Nullable<int> LegNo { get; set; }
        public Nullable<decimal> NoNetIncome { get; set; }
        public Nullable<decimal> Quint { get; set; }
        public Nullable<decimal> bal { get; set; }
        public Nullable<int> Orbit { get; set; }
        public Nullable<int> Stage { get; set; }
    }
}
