//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Binary_Orbit
    {
        public int Sno { get; set; }
        public int Orbit { get; set; }
        public int Step { get; set; }
        public int C1_Left { get; set; }
        public int C1_Right { get; set; }
        public int C2_Left { get; set; }
        public int C2_Right { get; set; }
        public decimal MatchedInc { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
