//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_WrkWeeklyRwd_Calc
    {
        public int Sno { get; set; }
        public decimal Regid { get; set; }
        public Nullable<int> Desgno { get; set; }
        public Nullable<int> PrvDesgno { get; set; }
        public Nullable<int> OrbitNo { get; set; }
        public Nullable<int> orbitStage { get; set; }
        public Nullable<int> OrbitCycle { get; set; }
        public Nullable<int> R1Left { get; set; }
        public Nullable<int> R1Right { get; set; }
        public Nullable<bool> Elg1Rwd { get; set; }
        public Nullable<int> R2Left { get; set; }
        public Nullable<int> R2Right { get; set; }
        public Nullable<bool> Elg2Rwd { get; set; }
        public Nullable<int> R3Left { get; set; }
        public Nullable<int> R3Right { get; set; }
        public Nullable<bool> Elg3Rwd { get; set; }
        public Nullable<int> R4Left { get; set; }
        public Nullable<int> R4Right { get; set; }
        public Nullable<bool> Elg4Rwd { get; set; }
        public Nullable<int> R5Left { get; set; }
        public Nullable<int> R5Right { get; set; }
        public Nullable<bool> Elg5Rwd { get; set; }
        public Nullable<int> R6Left { get; set; }
        public Nullable<int> R6Right { get; set; }
        public Nullable<bool> Elg6Rwd { get; set; }
        public Nullable<int> R7Left { get; set; }
        public Nullable<int> R7Right { get; set; }
        public Nullable<bool> Elg7Rwd { get; set; }
        public Nullable<int> R8Left { get; set; }
        public Nullable<int> R8Right { get; set; }
        public Nullable<bool> Elg8Rwd { get; set; }
        public Nullable<int> R9Left { get; set; }
        public Nullable<int> R9Right { get; set; }
        public Nullable<bool> Elg9Rwd { get; set; }
        public Nullable<int> R10Left { get; set; }
        public Nullable<int> R10Right { get; set; }
        public Nullable<bool> Elg10Rwd { get; set; }
        public Nullable<int> R11Left { get; set; }
        public Nullable<int> R11Right { get; set; }
        public Nullable<bool> Elg11Rwd { get; set; }
        public Nullable<int> R12Left { get; set; }
        public Nullable<int> R12Right { get; set; }
        public Nullable<bool> Elg12Rwd { get; set; }
        public Nullable<int> R13Left { get; set; }
        public Nullable<int> R13Right { get; set; }
        public Nullable<bool> Elg13Rwd { get; set; }
        public Nullable<int> R14Left { get; set; }
        public Nullable<int> R14Right { get; set; }
        public Nullable<bool> Elg14Rwd { get; set; }
    }
}
