//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_BVLaps_Id
    {
        public decimal Regid { get; set; }
        public Nullable<decimal> OldCFLeft { get; set; }
        public Nullable<decimal> OldCFRight { get; set; }
        public Nullable<decimal> NewCFLeft { get; set; }
        public Nullable<decimal> NewCFRight { get; set; }
        public decimal Payno { get; set; }
        public Nullable<System.DateTime> ClientMailDate { get; set; }
    }
}
