//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMP_RecCFAmt_RP
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string AmtType { get; set; }
        public Nullable<decimal> PayNo { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<decimal> UsedPayNo { get; set; }
        public string Remarks { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
