//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_WrkBV
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public Nullable<decimal> PrvSelfBV { get; set; }
        public Nullable<decimal> PrvGroupBV { get; set; }
        public Nullable<decimal> PrvTotalBV { get; set; }
        public Nullable<decimal> SelfBV { get; set; }
        public Nullable<decimal> GroupBV { get; set; }
        public Nullable<decimal> TotalBV { get; set; }
        public Nullable<int> DesgNo { get; set; }
        public Nullable<int> Rank_Dwn { get; set; }
        public Nullable<bool> Elg4Inc { get; set; }
        public Nullable<bool> Elg4Self { get; set; }
        public Nullable<bool> Elg4PB { get; set; }
        public Nullable<bool> Elg4A_SGF { get; set; }
        public Nullable<bool> Elg4A_TF { get; set; }
        public Nullable<bool> Elg4A_BF { get; set; }
        public Nullable<bool> Elg4A_CF { get; set; }
        public Nullable<bool> Elg4A_DVF { get; set; }
        public Nullable<bool> Elg4_R1 { get; set; }
        public Nullable<bool> Elg4_R2 { get; set; }
        public Nullable<bool> Elg4_R3 { get; set; }
        public Nullable<bool> Elg4_R4 { get; set; }
        public Nullable<bool> Elg4_R5 { get; set; }
        public Nullable<bool> Elg4Payment { get; set; }
        public int Cur_MStatus { get; set; }
    }
}
