//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Analysis
    {
        public int PayNo { get; set; }
        public decimal TurnOver { get; set; }
        public decimal Budget { get; set; }
        public decimal PayOut { get; set; }
        public decimal PayPer { get; set; }
    }
}
