//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMp_Rollback_Temp
    {
        public int Payno { get; set; }
        public int Uid { get; set; }
        public string Sessid { get; set; }
        public string Remarks { get; set; }
    }
}
