//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMP_OfferSSMP_20twenty_RP
    {
        public decimal Regid { get; set; }
        public Nullable<decimal> CBinc { get; set; }
        public Nullable<decimal> LeftBV { get; set; }
        public Nullable<decimal> RightBV { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> Payno { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
