//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_recCF_dontdel_Upto272
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public Nullable<decimal> TotLeft { get; set; }
        public Nullable<decimal> TotRight { get; set; }
        public Nullable<decimal> CFLeft { get; set; }
        public Nullable<decimal> CFRight { get; set; }
        public int OrbitNo { get; set; }
        public int OrbitStage { get; set; }
        public int OrbitCycle { get; set; }
        public Nullable<decimal> PayNo { get; set; }
        public int LeftCnt { get; set; }
        public int RightCnt { get; set; }
    }
}
