//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SICP_Monthly_UnitRate_RP
    {
        public decimal Payno { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> Exclusive_GCV { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string Inctype { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
