//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMP_RecBinary_Booster_RP
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public decimal Thru { get; set; }
        public int LegNo { get; set; }
        public Nullable<decimal> TotLeft { get; set; }
        public Nullable<decimal> TotRight { get; set; }
        public Nullable<decimal> BFLeft { get; set; }
        public Nullable<decimal> BFRight { get; set; }
        public Nullable<decimal> CurLeft { get; set; }
        public Nullable<decimal> CurRight { get; set; }
        public Nullable<decimal> RepCurLeft { get; set; }
        public Nullable<decimal> RepCurRight { get; set; }
        public Nullable<decimal> EPairs { get; set; }
        public Nullable<decimal> Elg_Left { get; set; }
        public Nullable<decimal> Elg_Right { get; set; }
        public Nullable<decimal> Elg_Pairs { get; set; }
        public Nullable<decimal> CFLeft { get; set; }
        public Nullable<decimal> CFRight { get; set; }
        public int OrbitNo { get; set; }
        public int OrbitStage { get; set; }
        public int OrbitCycle { get; set; }
        public int Prv_OrbitCycle { get; set; }
        public Nullable<decimal> BStrInc { get; set; }
        public Nullable<decimal> DirInc { get; set; }
        public Nullable<decimal> PrvEPairs { get; set; }
        public Nullable<bool> Elg4Inc { get; set; }
        public Nullable<bool> Elg4Bin { get; set; }
        public string OrbitSetValue { get; set; }
        public Nullable<decimal> PayNo { get; set; }
        public int LeftCnt { get; set; }
        public int RightCnt { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
        public string IDType { get; set; }
        public int Cur_MStatus { get; set; }
        public int Thru_MStatus { get; set; }
        public string PlanType { get; set; }
    }
}
