//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_monthly_RecGentlemanOffer
    {
        public decimal Regid { get; set; }
        public decimal Amt { get; set; }
        public decimal Payno { get; set; }
        public string Remarks { get; set; }
        public string InType { get; set; }
    }
}
