//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_WrkALLRoundDetails
    {
        public decimal RegId { get; set; }
        public int LegFrom { get; set; }
        public int LegTo { get; set; }
        public int LegMatched { get; set; }
    }
}
