//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SICP_Monthly_RecAristocracy_RP
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public int DesgNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Way { get; set; }
        public decimal PayNo { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
