//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_OrbitDetails_245
    {
        public decimal sessid { get; set; }
        public decimal formno { get; set; }
        public decimal triIncome { get; set; }
        public decimal nonetincome1 { get; set; }
        public decimal Quint1 { get; set; }
        public decimal nonetincome2 { get; set; }
        public decimal Quint2 { get; set; }
        public int Orbit { get; set; }
        public int Stage { get; set; }
        public int totalOrbits { get; set; }
    }
}
