//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Daily_RankBV
    {
        public decimal Regid { get; set; }
        public Nullable<decimal> PrvSelfBV { get; set; }
        public Nullable<decimal> PrvGroupBV { get; set; }
        public Nullable<decimal> PrvTotalBV { get; set; }
        public Nullable<decimal> SelfBV { get; set; }
        public Nullable<decimal> GroupBV { get; set; }
        public Nullable<decimal> TotalBV { get; set; }
        public Nullable<int> DesgNo { get; set; }
        public Nullable<int> PrvDesgno { get; set; }
        public Nullable<int> Rank_Dwn { get; set; }
        public Nullable<bool> Elg4Inc { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
