//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_OrbitDetails
    {
        public int RegId { get; set; }
        public int PayNo { get; set; }
        public Nullable<decimal> CurLeft { get; set; }
        public Nullable<decimal> CurRight { get; set; }
        public Nullable<decimal> Elg_Left { get; set; }
        public Nullable<decimal> Elg_Right { get; set; }
        public int OrbitNo { get; set; }
        public int OrbitStage { get; set; }
        public int OrbitCycle { get; set; }
        public int StepNo { get; set; }
    }
}
