//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_WrkBenDetails
    {
        public decimal RegId { get; set; }
        public Nullable<decimal> Exclusive_GCV { get; set; }
        public short DesgNo { get; set; }
        public Nullable<short> Lvl { get; set; }
        public string Inctype { get; set; }
        public Nullable<short> Elg4Inc { get; set; }
        public Nullable<short> ElgCnt { get; set; }
    }
}
