//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Record
    {
        public int SNo { get; set; }
        public Nullable<decimal> PayNo { get; set; }
        public Nullable<System.DateTime> SchFrom { get; set; }
        public Nullable<System.DateTime> SchTo { get; set; }
        public Nullable<System.DateTime> Session { get; set; }
        public int IDCnt { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> App_UId { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public string App_Sessid { get; set; }
        public int Weekno { get; set; }
        public string Sessid_Start { get; set; }
    }
}
