//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_WrkBenefits
    {
        public int SNo { get; set; }
        public decimal RegId { get; set; }
        public Nullable<decimal> Thru { get; set; }
        public Nullable<short> Lvl { get; set; }
        public Nullable<short> PayLvl { get; set; }
        public string IncType { get; set; }
        public Nullable<decimal> PCent { get; set; }
        public Nullable<decimal> PCentOnVol { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> Elg4Inc { get; set; }
    }
}
