//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_WrkLoyalDetails
    {
        public decimal RegId { get; set; }
        public Nullable<decimal> TotalBV { get; set; }
        public Nullable<decimal> Exclusive_GCV { get; set; }
        public short DesgNo { get; set; }
        public short Rankno { get; set; }
        public string Inctype { get; set; }
    }
}
