//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SSMP_RecRewardInc_RP
    {
        public decimal Regid { get; set; }
        public Nullable<decimal> PrvPV { get; set; }
        public Nullable<decimal> BFPV { get; set; }
        public Nullable<decimal> CurPV { get; set; }
        public Nullable<decimal> PayPV { get; set; }
        public Nullable<decimal> PayAmt { get; set; }
        public Nullable<decimal> CFPV { get; set; }
        public int Payno { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
