//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Monthly_Analysis
    {
        public decimal PayNo { get; set; }
        public Nullable<int> IDCnt { get; set; }
        public Nullable<int> RepCnt { get; set; }
        public Nullable<decimal> TotBV { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> TotPayout { get; set; }
        public Nullable<decimal> TotPer { get; set; }
        public Nullable<decimal> TotRetailBudget { get; set; }
        public Nullable<decimal> TotRetailComm { get; set; }
        public Nullable<decimal> TotGapBudget { get; set; }
        public Nullable<decimal> TotGapComm { get; set; }
        public Nullable<decimal> TotOvrBudget { get; set; }
        public Nullable<decimal> TotOvr { get; set; }
        public Nullable<decimal> TotPBBudget { get; set; }
        public Nullable<decimal> Totpb { get; set; }
        public Nullable<decimal> TotRsbBudget { get; set; }
        public Nullable<decimal> Totrs { get; set; }
        public Nullable<decimal> TotAstBudget { get; set; }
        public Nullable<decimal> TotAST { get; set; }
        public Nullable<decimal> TotRoyBudget { get; set; }
        public Nullable<decimal> TotROY { get; set; }
    }
}
