//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SICP_MOnthly_ConsiderBills_RP
    {
        public decimal Regid { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> challandt { get; set; }
        public Nullable<System.DateTime> Commdate { get; set; }
        public int MStatus { get; set; }
        public int PayNo { get; set; }
        public int Uid { get; set; }
        public string sessid { get; set; }
        public Nullable<System.DateTime> SessDate { get; set; }
    }
}
