//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayStatu
    {
        public int Sno { get; set; }
        public Nullable<bool> Paytm { get; set; }
        public Nullable<bool> EBS { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
