//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentreq
    {
        public decimal slno { get; set; }
        public string reqno { get; set; }
        public Nullable<decimal> regid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string sessid { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PlanType { get; set; }
        public string PayType { get; set; }
        public string POTraType { get; set; }
        public int Payno { get; set; }
        public string CHEQUENo { get; set; }
        public Nullable<System.DateTime> ChequeUpdateDate { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> ChqUpdatedDate { get; set; }
    }
}
