//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest_log
    {
        public decimal slno { get; set; }
        public string reqno { get; set; }
        public Nullable<decimal> regid { get; set; }
        public int Payno { get; set; }
        public string CHEQUENo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Bank { get; set; }
        public string NCHEQUENo { get; set; }
        public Nullable<System.DateTime> NChequeDate { get; set; }
        public string NBank { get; set; }
        public string Remarks { get; set; }
    }
}
