//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacementMaster
    {
        public int PMID { get; set; }
        public int Regid { get; set; }
        public int LeftS { get; set; }
        public int RightS { get; set; }
        public int Booster { get; set; }
        public Nullable<int> flag { get; set; }
        public string SessId { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
