//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSDispatchMaster
    {
        public int PDMID { get; set; }
        public string Billno { get; set; }
        public Nullable<int> DSid { get; set; }
        public Nullable<int> Regid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
    }
}
