//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_attributes_fields
    {
        public decimal Slno { get; set; }
        public string pcode { get; set; }
        public string Attribute_Name { get; set; }
        public string Field { get; set; }
        public string Sessid { get; set; }
    }
}
