//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int Pid { get; set; }
        public string Pcode { get; set; }
        public string Pname { get; set; }
        public string imageicon { get; set; }
        public string images { get; set; }
        public string thumbimage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string SessID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Ststus { get; set; }
    }
}
