//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public Nullable<decimal> CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string Activestatus { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public decimal Rownum { get; set; }
    }
}
