//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItems_CnF
    {
        public decimal slno { get; set; }
        public string RefNo { get; set; }
        public string Itemcode { get; set; }
        public string pcode { get; set; }
        public int Qty { get; set; }
        public decimal MRP { get; set; }
        public decimal DP { get; set; }
        public decimal CustomerPrice { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int status { get; set; }
        public string sesid { get; set; }
        public string UQID { get; set; }
        public string DispatchSts { get; set; }
        public decimal TransferPrice { get; set; }
        public decimal BP { get; set; }
        public decimal IGST_Rate { get; set; }
        public decimal IGST_Amt { get; set; }
        public decimal SGST_Rate { get; set; }
        public decimal SGST_Amt { get; set; }
        public decimal CGST_Rate { get; set; }
        public decimal CGST_Amt { get; set; }
        public int PackageId { get; set; }
    }
}
