//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVDetails_log
    {
        public int SNo { get; set; }
        public Nullable<int> regid { get; set; }
        public string billno { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<decimal> pv { get; set; }
        public Nullable<decimal> totalpv { get; set; }
        public string memtype { get; set; }
        public string mgroup { get; set; }
        public string plantype { get; set; }
    }
}
