//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVUpdtdRpt
    {
        public decimal regid { get; set; }
        public string idno { get; set; }
        public string name { get; set; }
        public System.DateTime memdate { get; set; }
        public int mstatus { get; set; }
        public System.DateTime stsdate { get; set; }
        public int CurPID { get; set; }
        public int OldPID { get; set; }
        public decimal CurPV { get; set; }
        public decimal OldPv { get; set; }
    }
}
