//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactDistMaster
    {
        public int RDMId { get; set; }
        public Nullable<int> Regid { get; set; }
        public Nullable<int> mstatus { get; set; }
        public Nullable<System.DateTime> Stsdate { get; set; }
        public string RegType { get; set; }
        public Nullable<int> KycID { get; set; }
        public string SessId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public Nullable<int> AppBy { get; set; }
        public Nullable<int> ReactDist { get; set; }
    }
}
