//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseDeviceLock_Log
    {
        public decimal PrId { get; set; }
        public decimal Regid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updatedby { get; set; }
        public string Imei { get; set; }
        public string Wlanmac { get; set; }
        public string Androidid { get; set; }
        public string GcmID { get; set; }
        public string SesID { get; set; }
    }
}
