//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepurchaseMaster_Reg
    {
        public int RMid { get; set; }
        public decimal SprRegID { get; set; }
        public decimal RegID { get; set; }
        public string Billno { get; set; }
        public System.DateTime BillDate { get; set; }
        public int TotQty { get; set; }
        public decimal TotPV { get; set; }
        public decimal TotalDP { get; set; }
        public decimal TotalBP { get; set; }
        public decimal TaxAmt { get; set; }
        public decimal NetAmt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public int status { get; set; }
        public string RegType { get; set; }
        public string RegThru { get; set; }
        public string RegFrom { get; set; }
        public string TaxType { get; set; }
        public string Sesid { get; set; }
        public string IpAddress { get; set; }
        public string UQID { get; set; }
        public int DishpatchSts { get; set; }
        public decimal RMidM { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string Fcode { get; set; }
        public decimal TotCV { get; set; }
        public string ReceiverAddr { get; set; }
        public string PackCode { get; set; }
        public decimal RegKitAmt { get; set; }
        public decimal ShipAmt { get; set; }
        public decimal CODAmt { get; set; }
        public decimal TRMid { get; set; }
        public string DispatchMode { get; set; }
        public string OrderThru { get; set; }
    }
}
