//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepurchIncomeExt
    {
        public decimal Aid { get; set; }
        public decimal SessId { get; set; }
        public decimal FormNo { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal BillAmt { get; set; }
        public decimal RepurchIncome { get; set; }
        public decimal Imported { get; set; }
        public string BillType { get; set; }
        public string SoldBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
