//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class repurchasesale
    {
        public decimal slno { get; set; }
        public string billno { get; set; }
        public decimal regid { get; set; }
        public System.DateTime billdate { get; set; }
        public string pcode { get; set; }
        public string pname { get; set; }
        public int qty { get; set; }
        public decimal amount { get; set; }
        public string code { get; set; }
        public string sesid { get; set; }
        public Nullable<decimal> pv { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> BasicRate { get; set; }
        public Nullable<decimal> DDPCommission { get; set; }
        public Nullable<double> Vat { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public string taxper { get; set; }
        public string taxtype { get; set; }
        public Nullable<decimal> taxamt { get; set; }
        public string itemcode { get; set; }
        public string Attribute { get; set; }
        public Nullable<int> offerqty { get; set; }
        public Nullable<int> ReturnSts { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public int FreePrd { get; set; }
    }
}
