//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepurchIncomeold
    {
        public decimal SessId { get; set; }
        public decimal FormNo { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal RepurchIncome { get; set; }
        public string Imported { get; set; }
        public decimal Msessid { get; set; }
        public decimal SNo { get; set; }
        public decimal LegNo { get; set; }
        public string type { get; set; }
        public decimal PSessid { get; set; }
        public decimal ECode { get; set; }
        public decimal PNo { get; set; }
        public string AppType { get; set; }
        public decimal regid { get; set; }
    }
}
