//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class repurchaseproducts_log
    {
        public int RpPid { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> PV { get; set; }
        public Nullable<decimal> Shpchrg { get; set; }
        public string Descr { get; set; }
        public Nullable<int> RPCID { get; set; }
        public Nullable<int> Attr { get; set; }
        public string Alias { get; set; }
        public Nullable<int> PStatus { get; set; }
        public Nullable<bool> myChoice { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string SesId { get; set; }
        public string PlanType { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string SubCategoryone { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedtedBy { get; set; }
        public string Brand { get; set; }
        public string ShopInfo { get; set; }
        public Nullable<decimal> offprice { get; set; }
        public Nullable<decimal> DPPercentage { get; set; }
        public Nullable<decimal> DP { get; set; }
        public string HSNO { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
    }
}
