//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMop
    {
        public decimal slno { get; set; }
        public string ReqNo { get; set; }
        public string Mop { get; set; }
        public System.DateTime reqdate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> crchrg { get; set; }
        public string sesid { get; set; }
    }
}
