//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrder
    {
        public decimal slno { get; set; }
        public string ReqNo { get; set; }
        public decimal regid { get; set; }
        public System.DateTime reqdate { get; set; }
        public string pcode { get; set; }
        public int qty { get; set; }
        public decimal price { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> Ostatus { get; set; }
        public Nullable<decimal> pv { get; set; }
        public string Remarks { get; set; }
        public string Apprejby { get; set; }
        public Nullable<System.DateTime> AppRejDate { get; set; }
        public string Ordertype { get; set; }
        public string sesid { get; set; }
        public Nullable<decimal> crchrg { get; set; }
        public string BillType { get; set; }
        public string Attrib { get; set; }
        public string Itemcode { get; set; }
    }
}
