//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPassword
    {
        public int RPId { get; set; }
        public decimal Regid { get; set; }
        public int PwdType { get; set; }
        public bool sms { get; set; }
        public bool Changed { get; set; }
        public int CPId { get; set; }
    }
}
