//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpcategory
    {
        public int RPCId { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string SubCategoryone { get; set; }
        public string SubCategorytwo { get; set; }
        public Nullable<bool> cstatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public string Sesid { get; set; }
        public Nullable<int> sorting { get; set; }
    }
}
