//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rwd_SSNP_Baleno_RwdDetails
    {
        public decimal Regid { get; set; }
        public System.DateTime JDate { get; set; }
        public System.DateTime RDate { get; set; }
        public Nullable<int> NoofDays { get; set; }
        public System.DateTime SDate { get; set; }
        public System.DateTime EDate { get; set; }
        public Nullable<int> DesgNo { get; set; }
        public Nullable<bool> Elg4Bin { get; set; }
        public Nullable<bool> Elg4Inc { get; set; }
        public Nullable<decimal> TotalLBV { get; set; }
        public Nullable<decimal> TotalRBV { get; set; }
        public Nullable<decimal> LeftBV { get; set; }
        public Nullable<decimal> RightBV { get; set; }
        public Nullable<int> LeftAchCnt { get; set; }
        public Nullable<int> RightAchCnt { get; set; }
        public Nullable<bool> Elg4SSMP { get; set; }
        public System.DateTime PrcdUpto { get; set; }
    }
}
