//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTempReg
    {
        public int Sno { get; set; }
        public string Idno { get; set; }
        public string UserName { get; set; }
        public Nullable<int> sprno { get; set; }
        public Nullable<int> spseries { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public Nullable<long> Pin { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string LPassword { get; set; }
        public string TPassword { get; set; }
        public string PanNo { get; set; }
        public string Title { get; set; }
        public string Maiden { get; set; }
        public string MaidenName { get; set; }
        public string SesId { get; set; }
    }
}
