//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCOnline
    {
        public decimal Sno { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string mobile { get; set; }
        public string ORDER_ID { get; set; }
        public string PaymentStatus { get; set; }
        public string BillStatus { get; set; }
        public string TXNID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string pgtype { get; set; }
        public Nullable<decimal> shpcharge { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public Nullable<int> modifystatus { get; set; }
        public string PGTranStatus { get; set; }
        public string scmemtype { get; set; }
        public string CCRemarks { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string couponcode { get; set; }
        public string ItemCodes { get; set; }
    }
}
