//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionsInOut
    {
        public int sno { get; set; }
        public Nullable<int> uid { get; set; }
        public string sesid { get; set; }
        public string ipaddress { get; set; }
        public string systemname { get; set; }
        public Nullable<System.DateTime> Sesin { get; set; }
        public Nullable<System.DateTime> SesOut { get; set; }
        public string usertype { get; set; }
    }
}
