//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoppingaddress
    {
        public int SAId { get; set; }
        public Nullable<decimal> Regid { get; set; }
        public string Reqno { get; set; }
        public string Billno { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string state { get; set; }
        public string PiCode { get; set; }
    }
}
