//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCartRandomNo
    {
        public decimal Sno { get; set; }
        public Nullable<decimal> RandomNo { get; set; }
        public Nullable<int> status { get; set; }
    }
}
