//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public decimal sno { get; set; }
        public decimal regid { get; set; }
        public string Pcode { get; set; }
        public int qty { get; set; }
        public string Attribute { get; set; }
        public string itemcode { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string reqno { get; set; }
        public Nullable<System.DateTime> scdate { get; set; }
        public Nullable<bool> scstatus { get; set; }
        public string Ordertype { get; set; }
        public string sesid { get; set; }
        public string ipadd { get; set; }
    }
}
