//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SICPEWalletComm
    {
        public decimal SNo { get; set; }
        public decimal RegId { get; set; }
        public Nullable<decimal> InAmt { get; set; }
        public Nullable<decimal> OutAmt { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Descr { get; set; }
        public string Remarks { get; set; }
        public string TypeOfInc { get; set; }
        public string Thru { get; set; }
        public Nullable<decimal> PayNo { get; set; }
        public string SessId { get; set; }
        public string RefID { get; set; }
    }
}
