//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulation_MemberLogic
    {
        public int RegId { get; set; }
        public int SprNo { get; set; }
        public int Leg { get; set; }
        public int MStatus { get; set; }
        public Nullable<System.DateTime> StsDate { get; set; }
    }
}
