//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class smslog
    {
        public int sno { get; set; }
        public Nullable<decimal> regid { get; set; }
        public Nullable<System.DateTime> senddate { get; set; }
        public string smstype { get; set; }
        public string mobile { get; set; }
        public string message { get; set; }
        public string sesid { get; set; }
        public string SendTo { get; set; }
    }
}
