//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorchange_SBOIDS
    {
        public int SNo { get; set; }
        public decimal Regid { get; set; }
        public Nullable<System.DateTime> Gendate { get; set; }
    }
}
