//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Member_Reg
    {
        public int Sno { get; set; }
        public decimal FormNo { get; set; }
        public decimal UpLnFormNo { get; set; }
        public int LegNo { get; set; }
        public int SprCnt { get; set; }
        public decimal RegCV { get; set; }
        public int RegStatus { get; set; }
        public Nullable<System.DateTime> RegStsdate { get; set; }
    }
}
