//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Orbit_test_booster
    {
        public decimal uplnformno { get; set; }
        public decimal FormNo { get; set; }
        public decimal LegNo { get; set; }
        public Nullable<decimal> NoNetIncome2 { get; set; }
        public Nullable<decimal> Quint2 { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public int Orbit { get; set; }
        public int Stage { get; set; }
    }
}
