//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public int SMId { get; set; }
        public Nullable<int> stsid { get; set; }
        public string Mstatus { get; set; }
        public string Astatus { get; set; }
        public string SarsoStatus { get; set; }
    }
}
