//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class STNAddress
    {
        public decimal STNAId { get; set; }
        public Nullable<int> STnType { get; set; }
        public string RefNo { get; set; }
        public string Fname { get; set; }
        public string CPName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string tinno { get; set; }
        public string VatNo { get; set; }
        public string CSTNo { get; set; }
        public string GSTNo { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
