//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrder
    {
        public decimal slno { get; set; }
        public string RefNo { get; set; }
        public string FCode { get; set; }
        public string CFCPCode { get; set; }
        public string DFCPCode { get; set; }
        public string SFCPCode { get; set; }
        public string packcode { get; set; }
        public string ItemCode { get; set; }
        public int qty { get; set; }
        public decimal price { get; set; }
        public decimal amount { get; set; }
        public System.DateTime RefDate { get; set; }
        public string Remarks { get; set; }
        public string status { get; set; }
        public string sesid { get; set; }
        public string TranRefNo { get; set; }
        public string OrdType { get; set; }
        public string OrdFor { get; set; }
        public string pcode { get; set; }
    }
}
