//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stockreturn
    {
        public int slno { get; set; }
        public Nullable<int> Regid { get; set; }
        public string RefNo { get; set; }
        public string ItemCode { get; set; }
        public string Code { get; set; }
        public Nullable<int> qty { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public string sesid { get; set; }
        public string TransType { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> AppRejDate { get; set; }
        public string Billno { get; set; }
        public string SRemarks { get; set; }
        public string StoreSSid { get; set; }
    }
}
