//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjust_FCP
    {
        public decimal slno { get; set; }
        public string RefNo { get; set; }
        public string FCode { get; set; }
        public string packcode { get; set; }
        public string ItemCode { get; set; }
        public int Inward { get; set; }
        public int Outward { get; set; }
        public System.DateTime RefDate { get; set; }
        public string Remarks { get; set; }
        public string sesid { get; set; }
        public string AdjustType { get; set; }
    }
}
