//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class storeuser
    {
        public int Sid { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedby { get; set; }
        public Nullable<System.DateTime> LastUpdatedate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
    }
}
