//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreUserList
    {
        public int SlId { get; set; }
        public int SId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastDateOfUpdation { get; set; }
        public string sesid { get; set; }
        public string Idaddress { get; set; }
        public string GSTNo { get; set; }
        public string Pincode { get; set; }
    }
}
