//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stp_PayoutIncomes
    {
        public decimal regid { get; set; }
        public Nullable<decimal> RetailProfit { get; set; }
        public Nullable<decimal> LVBonus { get; set; }
        public Nullable<decimal> OverridingBonus { get; set; }
        public Nullable<decimal> ResidualBonus { get; set; }
        public Nullable<decimal> PerformanceBonus { get; set; }
        public Nullable<decimal> AristocracyBonus { get; set; }
        public Nullable<decimal> RoyaltyBonus { get; set; }
        public Nullable<decimal> MRSBonus { get; set; }
        public Nullable<decimal> PoolPBonus { get; set; }
        public Nullable<decimal> ALBonus { get; set; }
        public Nullable<decimal> LOYALBonus { get; set; }
        public Nullable<decimal> ROYALBonus { get; set; }
        public Nullable<decimal> SICPOfferInc { get; set; }
        public Nullable<decimal> SICPTTInc { get; set; }
        public Nullable<decimal> TotalIncome { get; set; }
        public decimal payno { get; set; }
    }
}
