//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stp_Weeklypayout
    {
        public decimal regid { get; set; }
        public Nullable<decimal> Binc { get; set; }
        public Nullable<decimal> RewardIncome { get; set; }
        public Nullable<decimal> Bstrinc { get; set; }
        public Nullable<decimal> DirInc { get; set; }
        public Nullable<decimal> DiwaliSprInc { get; set; }
        public Nullable<decimal> SSMPOfferInc { get; set; }
        public Nullable<int> payno { get; set; }
    }
}
