//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWalletShopping
    {
        public decimal SNo { get; set; }
        public decimal Formno { get; set; }
        public decimal Amount { get; set; }
        public string ProductName { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public decimal PNo { get; set; }
        public decimal ProductId { get; set; }
        public decimal Qty { get; set; }
        public decimal Cv { get; set; }
        public string PayMode { get; set; }
        public string MCode { get; set; }
        public string MPOSHName { get; set; }
        public string TIDNo { get; set; }
        public string IssueBranch { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public decimal BID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public decimal DDAmount { get; set; }
        public string DDNo { get; set; }
        public string PStatus { get; set; }
        public string IsPaymentConform { get; set; }
        public decimal Session { get; set; }
        public string Mode { get; set; }
        public decimal TId { get; set; }
        public decimal LegNo { get; set; }
        public decimal CntUpdate { get; set; }
        public Nullable<System.DateTime> IsPaymentConformDate { get; set; }
        public decimal PSessid { get; set; }
        public string Size { get; set; }
        public decimal ECode { get; set; }
        public string IsPaymentComplete { get; set; }
        public decimal UpgrdSessid { get; set; }
        public string Color { get; set; }
        public string Isdeliver { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public decimal BillNo { get; set; }
        public string InvBillNo { get; set; }
        public decimal Fsessid { get; set; }
        public decimal SBOPrice { get; set; }
        public decimal Mrp { get; set; }
        public string ShippingAddress { get; set; }
        public string CouponName { get; set; }
        public decimal CouponCode { get; set; }
        public decimal totalamount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string VoucherUserId { get; set; }
        public string VoucherPassword { get; set; }
        public decimal InvoiceNo { get; set; }
        public string InvNo { get; set; }
        public string InvoiceStatus { get; set; }
        public string PurchaseStatus { get; set; }
        public string SpecialRequest { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public decimal ShippingPinCode { get; set; }
        public string HostIP { get; set; }
        public string AppType { get; set; }
        public Nullable<decimal> SICPCV { get; set; }
        public string Istransdetail { get; set; }
    }
}
