//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCart_log
    {
        public int Sno { get; set; }
        public string Pcode { get; set; }
        public string ItemCode { get; set; }
        public string Attribute { get; set; }
        public Nullable<int> Qty { get; set; }
        public string UNQId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
