//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrder
    {
        public int Sno { get; set; }
        public string UNQid { get; set; }
        public Nullable<decimal> regid { get; set; }
        public Nullable<decimal> downlineid { get; set; }
        public string mop { get; set; }
        public Nullable<decimal> mopamt { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string state { get; set; }
        public string PiCode { get; set; }
        public string Ordertype { get; set; }
        public Nullable<decimal> shpchrg { get; set; }
        public string scmemtype { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
