//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempInvOfferPrd
    {
        public int slno { get; set; }
        public Nullable<int> sno { get; set; }
        public Nullable<int> pcode { get; set; }
        public string itemcode { get; set; }
        public string sesid { get; set; }
        public string uqid { get; set; }
        public Nullable<int> regid { get; set; }
        public string attrname { get; set; }
    }
}
