//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempLegShift
    {
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal MLevel { get; set; }
        public decimal Leg { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal SpSeries { get; set; }
    }
}
