//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOfferproduct
    {
        public int Sno { get; set; }
        public Nullable<decimal> Regid { get; set; }
        public string Unqid { get; set; }
        public Nullable<int> Pcode { get; set; }
    }
}
