//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempAddToCart_log
    {
        public int Slno { get; set; }
        public string Pcode { get; set; }
        public string itemcode { get; set; }
        public Nullable<int> AvailQty { get; set; }
        public Nullable<int> OrdQty { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
