//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempEditOrders_Log
    {
        public int RpPid { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Descr { get; set; }
        public string ItemCode { get; set; }
        public string Attrib1 { get; set; }
        public string Attrib2 { get; set; }
        public string Attrib3 { get; set; }
        public string Attrib4 { get; set; }
        public string Attrib5 { get; set; }
        public string Attrib6 { get; set; }
        public string Attrib7 { get; set; }
        public string Attrib8 { get; set; }
        public string Attrib9 { get; set; }
        public string Attrib10 { get; set; }
        public Nullable<int> OrdQty { get; set; }
        public Nullable<int> AvailQty { get; set; }
        public Nullable<int> PStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string reqno { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> OrdDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string packcode { get; set; }
        public string Billno { get; set; }
        public string Prdtype { get; set; }
    }
}
