//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCourier
    {
        public int Sno { get; set; }
        public string Regid { get; set; }
        public string UNQId { get; set; }
        public string Courier { get; set; }
        public Nullable<int> Sts { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
