//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_RREP_oldBillDatainfo_DontDel_3
    {
        public decimal Memno { get; set; }
        public string billno { get; set; }
        public Nullable<int> cnt { get; set; }
        public string plantype { get; set; }
        public string memtype { get; set; }
    }
}
