//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpPackageItem
    {
        public decimal slno { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string randomno { get; set; }
        public decimal rpcid { get; set; }
        public string pcode { get; set; }
        public string Offtype { get; set; }
        public Nullable<decimal> CV { get; set; }
        public Nullable<decimal> GSTPrice { get; set; }
    }
}
