//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPaymentOnline
    {
        public decimal TID { get; set; }
        public decimal Amount { get; set; }
        public string FNAme { get; set; }
        public string LastName { get; set; }
        public string EmailkId { get; set; }
        public string Address { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TxnRefNo { get; set; }
        public decimal TCode { get; set; }
        public string IsFlaged { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public string ResponseMessage { get; set; }
        public long PaymentId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserName { get; set; }
        public string Mode { get; set; }
        public string CancelStatus { get; set; }
        public string IsCheck { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public decimal SysOrderNo { get; set; }
        public string AppType { get; set; }
    }
}
