//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateDist
    {
        public int SNo { get; set; }
        public Nullable<int> Regid { get; set; }
        public string Sessid { get; set; }
        public string Type { get; set; }
        public Nullable<int> Uid { get; set; }
    }
}
