//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateCourierlog
    {
        public int SNo { get; set; }
        public int Regid { get; set; }
        public string InvoiceNo { get; set; }
        public string OCourName { get; set; }
        public string ODockNo { get; set; }
        public string CourName { get; set; }
        public string DockNo { get; set; }
        public int UpdatedBy { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
