//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Address
    {
        public string idno { get; set; }
        public decimal regid { get; set; }
        public string Name { get; set; }
        public string PermanentADD { get; set; }
        public string CorrespondenceADD { get; set; }
        public string CorrespondenceADD1 { get; set; }
        public string CorrespondenceADD2 { get; set; }
        public string Mobile { get; set; }
        public string AltMobile { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public string Billno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> challandt { get; set; }
        public string Despstatus { get; set; }
    }
}
