//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Distlist
    {
        public string idno { get; set; }
        public decimal regid { get; set; }
        public string NAME { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public System.DateTime Joindate { get; set; }
        public Nullable<decimal> CV { get; set; }
        public Nullable<System.DateTime> LastPurdate { get; set; }
        public Nullable<System.DateTime> LastdateDist { get; set; }
        public Nullable<decimal> BV { get; set; }
        public string Status { get; set; }
        public string SSMPRank { get; set; }
    }
}
