//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PaymentOnline
    {
        public decimal Amount { get; set; }
        public decimal TxnRefNo { get; set; }
        public decimal TCode { get; set; }
        public string ResponseMessage { get; set; }
        public long PaymentId { get; set; }
        public string mode { get; set; }
        public string IsCheck { get; set; }
        public string IsFlaged { get; set; }
        public string CancelStatus { get; set; }
    }
}
