//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StoreKitId
    {
        public Nullable<decimal> Formno { get; set; }
        public decimal ProductId { get; set; }
        public string MemName { get; set; }
        public decimal MPId { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public decimal Bv { get; set; }
        public decimal Qty { get; set; }
        public string Paymode { get; set; }
        public Nullable<decimal> MerRefNo { get; set; }
        public string MCode { get; set; }
        public Nullable<System.DateTime> MSwipeDate { get; set; }
        public string ChDDNo { get; set; }
        public string TIDNO { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Kitamount { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string MPOS { get; set; }
        public Nullable<decimal> Session { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public string DISPFORMNO { get; set; }
        public string PaymentBranchName { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> PaymentBankID { get; set; }
    }
}
