//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tickets
    {
        public string SBOID { get; set; }
        public string Name { get; set; }
        public string reqno { get; set; }
        public string dept { get; set; }
        public string Relatedto { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Updatedby { get; set; }
        public System.DateTime updateddate { get; set; }
        public string status { get; set; }
        public string ReadSts { get; set; }
    }
}
