//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers_Admin
    {
        public int VNo { get; set; }
        public string VoucherType { get; set; }
        public string VoucherID { get; set; }
        public string VoucherPswd { get; set; }
        public int Pid { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
    }
}
