//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarsoShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SSMP_All
    {
        public decimal RegId { get; set; }
        public Nullable<decimal> PV { get; set; }
        public string MemType { get; set; }
        public Nullable<System.DateTime> Memdate { get; set; }
    }
}
